<?php

$ranksetNames["touhou"] = "Touhou Project";

$ranksetData["touhou"] = array(
	array("num" => 0, "image" => '', "text" => 'Non-poster'),
	array("num" => 1, "image" => '', "text" => 'Newcomer'),
	array("num" => 10, "image" => 'kedama.png', "text" => 'Kedama'),
	array("num" => 25, "image" => 'yinyang.png', "text" => 'Yin-Yang Orb'),
	array("num" => 40, "image" => 'fairy.png', "text" => 'Fairy'),
	array("num" => 55, "image" => 'bigfairy.png', "text" => 'Big Fairy'),
	array("num" => 70, "image" => 'makaifairy.png', "text" => 'Makai Fairy'),
	array("num" => 85, "image" => 'bigmakaifairy.png', "text" => 'Big Makai Fairy'),
	array("num" => 100, "image" => 'spirit.png', "text" => 'Divine Spirit'),
	array("num" => 115, "image" => 'ufo.png', "text" => 'UFO'),
	array("num" => 130, "image" => 'lilywhite.png', "text" => 'Lily White'),
	array("num" => 150, "image" => 'rumia.png', "text" => 'Rumia'),
	array("num" => 175, "image" => 'letty.png', "text" => 'Letty Whiterock'),
	array("num" => 200, "image" => 'wriggle.png', "text" => 'Wriggle Nightbug'),
	array("num" => 225, "image" => 'shizuha.png', "text" => 'Shizuha Aki'),
	array("num" => 250, "image" => 'minoriko.png', "text" => 'Minoriko Aki'),
	array("num" => 275, "image" => 'kisume.png', "text" => 'Kisume'),
	array("num" => 300, "image" => 'yamame.png', "text" => 'Yamame Kurodani'),
	array("num" => 325, "image" => 'nazrin.png', "text" => 'Nazrin'),
	array("num" => 350, "image" => 'wakasagihime.png', "text" => 'Wakasagihime'),
	array("num" => 375, "image" => 'cirno.png', "text" => 'Cirno'),
	array("num" => 400, "image" => 'chen.png', "text" => 'Chen'),
	array("num" => 425, "image" => 'mystia.png', "text" => 'Mystia Lorelei'),
	array("num" => 450, "image" => 'hina.png', "text" => 'Hina Kagiyama'),
	array("num" => 475, "image" => 'parsee.png', "text" => 'Parsee Mizuhashi'),
	array("num" => 500, "image" => 'kogasa.png', "text" => 'Kogasa Tatara'),
	array("num" => 525, "image" => 'kyouko.png', "text" => 'Kyouko Kasodani'),
	array("num" => 550, "image" => 'sekibanki.png', "text" => 'Sekibanki'),
	array("num" => 575, "image" => 'meiling.png', "text" => 'Hong Meiling'),
	array("num" => 600, "image" => 'alice.png', "text" => 'Alice Margatroid'),
	array("num" => 625, "image" => 'keine.png', "text" => 'Keine Kamishirasawa'),
	array("num" => 650, "image" => 'medicine.png', "text" => 'Medicine Melancholy'),
	array("num" => 675, "image" => 'nitori.png', "text" => 'Nitori Kawashiro'),
	array("num" => 700, "image" => 'yuugi.png', "text" => 'Yuugi Hoshiguma'),
	array("num" => 725, "image" => 'ichirin.png', "text" => 'Ichirin Kumoi'),
	array("num" => 750, "image" => 'yoshika.png', "text" => 'Yoshika Miyako'),
	array("num" => 775, "image" => 'kagerou.png', "text" => 'Kagerou Imaizumi'),
	array("num" => 800, "image" => 'patchouli.png', "text" => 'Patchouli Knowledge'),
	array("num" => 825, "image" => 'lyrica.png', "text" => 'Lyrica Prismriver'),
	array("num" => 850, "image" => 'merlin.png', "text" => 'Merlin Prismriver'),
	array("num" => 875, "image" => 'lunasa.png', "text" => 'Lunasa Prismriver'),
	array("num" => 900, "image" => 'tewi.png', "text" => 'Tewi Inaba'),
	array("num" => 925, "image" => 'momiji.png', "text" => 'Momiji Inubashiri'),
	array("num" => 950, "image" => 'aya.png', "text" => 'Aya Shameimaru'),
	array("num" => 975, "image" => 'hatate.png', "text" => 'Hatate Himekaidou'),
	array("num" => 1000, "image" => 'satori.png', "text" => 'Satori Komeiji'),
	array("num" => 1025, "image" => 'minamitsu.png', "text" => 'Minamitsu Murasa'),
	array("num" => 1050, "image" => 'seiga.png', "text" => 'Seiga Kaku'),
	array("num" => 1075, "image" => 'benben.png', "text" => 'Benben Tsukumo'),
	array("num" => 1100, "image" => 'yatsuhashi.png', "text" => 'Yatsuhashi Tsukumo'),
	array("num" => 1125, "image" => 'sakuya.png', "text" => 'Sakuya Izayoi'),
	array("num" => 1150, "image" => 'youmu.png', "text" => 'Youmu Konpaku'),
	array("num" => 1175, "image" => 'reisen.png', "text" => 'Reisen U. Inaba'),
	array("num" => 1200, "image" => 'komachi.png', "text" => 'Komachi Onozuka'),
	array("num" => 1225, "image" => 'sanae.png', "text" => 'Sanae Kochiya'),
	array("num" => 1250, "image" => 'iku.png', "text" => 'Iku Nagae'),
	array("num" => 1275, "image" => 'orin.png', "text" => 'Rin Kaenbyou'),
	array("num" => 1300, "image" => 'shou.png', "text" => 'Shou Toramaru'),
	array("num" => 1325, "image" => 'tojiko.png', "text" => 'Soga no Tojiko'),
	array("num" => 1350, "image" => 'futo.png', "text" => 'Mononobe no Futo'),
	array("num" => 1375, "image" => 'seija.png', "text" => 'Seija Kijin'),
	array("num" => 1400, "image" => 'remilia.png', "text" => 'Remilia Scarlet'),
	array("num" => 1425, "image" => 'yuyuko.png', "text" => 'Yuyuko Saigyouji'),
	array("num" => 1450, "image" => 'eirin.png', "text" => 'Eirin Yagokoro'),
	array("num" => 1475, "image" => 'kaguya.png', "text" => 'Kaguya Houraisan'),
	array("num" => 1500, "image" => 'eiki.png', "text" => 'Eiki Shiki'),
	array("num" => 1525, "image" => 'kanako.png', "text" => 'Kanako Yasaka'),
	array("num" => 1550, "image" => 'tenshi.png', "text" => 'Tenshi Hinanawi'),
	array("num" => 1575, "image" => 'utsuho.png', "text" => 'Utsuho Reiuji'),
	array("num" => 1600, "image" => 'byakuren.png', "text" => 'Byakuren Hijiri'),
	array("num" => 1625, "image" => 'miko.png', "text" => 'Toyosatomimi no Miko'),
	array("num" => 1650, "image" => 'yuka.png', "text" => 'Yuuka Kazami'),
	array("num" => 1675, "image" => 'shinmyoumaru.png', "text" => 'Shinmyoumaru Sukuna'),
	array("num" => 1700, "image" => 'flandre.png', "text" => 'Flandre Scarlet'),
	array("num" => 1725, "image" => 'ran.png', "text" => 'Ran Yakumo'),
	array("num" => 1750, "image" => 'exkeine.png', "text" => 'Keine Kamishirasawa'),
	array("num" => 1775, "image" => 'mokou.png', "text" => 'Fujiwara Mokou'),
	array("num" => 1800, "image" => 'suwako.png', "text" => 'Suwako Moriya'),
	array("num" => 1825, "image" => 'koishi.png', "text" => 'Koishi Komeiji'),
	array("num" => 1850, "image" => 'nue.png', "text" => 'Nue Houjuu'),
	array("num" => 1875, "image" => 'mamizou.png', "text" => 'Mamizou Futatsuiwa'),
	array("num" => 1900, "image" => 'raiko.png', "text" => 'Raiko Horikawa'),
	array("num" => 1925, "image" => 'suika.png', "text" => 'Suika Ibuki'),
	array("num" => 1950, "image" => 'marisa.png', "text" => 'Marisa Kirisame'),
	array("num" => 1975, "image" => 'reimu.png', "text" => 'Reimu Hakurei'),
	array("num" => 2000, "image" => 'yukari.png', "text" => 'Yukari Yakumo'),
	array("num" => 2500, "image" => 'reimu2.png', "text" => 'Reimu Hakurei (CtC)'),
	array("num" => 3000, "image" => 'gensokyo.png', "text" => 'Phantasm, Foam and Shadow'),
);
